In [1]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import StandardScaler

In [2]:
data = pd.read_csv('fraudTrain.csv')

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 23 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Unnamed: 0             1296675 non-null  int64
 1   trans_date_trans_time  1296675 non-null  object
 2   cc_num                 1296675 non-null  int64
 3   merchant               1296675 non-null  object
 4   category               1296675 non-null  object
 5   amt                    1296675 non-null  float64
 6   first                  1296675 non-null  object
 7   last                   1296675 non-null  object
 8   gender                 1296675 non-null  object
 9   street                 1296675 non-null  object
 10  city                   1296675 non-null  object
 11  state                  1296675 non-null  object
 12  zip                    1296675 non-null  int64
 13  lat                    1296675 non-null  float64
 14  long                   1296675 non-null  float64
 15  city_pop               1296675 non-null  int64
 16  job                    1296675 non-null  object
 17  dob                    1296675 non-null  object
 18  trans_num              1296675 non-null  object
 19  unix_time              1296675 non-null  int64
 20  merch_lat              1296675 non-null  float64
 21  merch_long             1296675 non-null  float64
 22  is_fraud               1296675 non-null  int64
dtypes: float64(5), int64(6), object(12)
memory usage: 227.5+ MB

In [4]:
data.head(2)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0

In [5]:
data.isnull().sum()

Unnamed: 0               0
trans_date_trans_time    0
cc_num                   0
merchant                 0
category                 0
amt                      0
first                    0
last                     0
gender                   0
street                   0
city                     0
state                    0
zip                      0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
unix_time                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [6]:
data.describe()

,Unnamed: 0,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,is_fraud
count,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06,1.296675e+06
mean,6.483370e+05,4.171920e+17,7.035104e+01,4.880067e+04,3.853762e+01,-9.022634e+01,8.882444e+04,1.349244e+09,3.853734e+01,-9.022646e+01,5.788652e-03
std,3.743180e+05,1.308806e+18,1.603160e+02,2.689322e+04,5.075808e+00,1.375908e+01,3.019564e+05,1.284128e+07,5.109788e+00,1.377109e+01,7.586269e-02
min,0.000000e+00,6.041621e+10,1.000000e+00,1.257000e+03,2.002710e+01,-1.656723e+02,2.300000e+01,1.325376e+09,1.902779e+01,-1.666712e+02,0.000000e+00
25%,3.241685e+05,1.800429e+14,9.650000e+00,2.623700e+04,3.462050e+01,-9.679800e+01,7.430000e+02,1.338751e+09,3.473357e+01,-9.689728e+01,0.000000e+00
50%,6.483370e+05,3.521417e+15,4.752000e+01,4.817400e+04,3.935430e+01,-8.747690e+01,2.456000e+03,1.349250e+09,3.936568e+01,-8.743839e+01,0.000000e+00
75%,9.725055e+05,4.642255e+15,8.314000e+01,7.204200e+04,4.194040e+01,-8.015800e+01,2.032800e+04,1.359385e+09,4.195716e+01,-8.023680e+01,0.000000e+00
max,1.296674e+06,4.992346e+18,2.894890e+04,9.978300e+04,6.669330e+01,-6.795030e+01,2.906700e+06,1.371817e+09,6.751027e+01,-6.695090e+01,1.000000e+00

In [7]:
unscaled_data = data.copy()

In [8]:
unscaled_data.head(2)

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0

In [9]:
unscaled_data['trans_date_trans_time']= pd.to_datetime(unscaled_data['trans_date_trans_time'])

unscaled_data['month'] = unscaled_data['trans_date_trans_time'].dt.month
unscaled_data['day_of_week'] = unscaled_data['trans_date_trans_time'].dt.day_of_week
unscaled_data['hours']= unscaled_data['trans_date_trans_time'].dt.hour

In [10]:
unscaled_data

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,month,day_of_week,hours
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,1,1,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,1,1,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,1,1,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,1,1,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,1296670,2020-06-21 12:12:08,30263540414123,fraud_Reichel Inc,entertainment,15.56,Erik,Patterson,M,162 Jessica Row Apt. 072,...,Geoscientist,1961-11-24,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0,6,6,12
1296671,1296671,2020-06-21 12:12:19,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,Jeffrey,White,M,8617 Holmes Terrace Suite 651,...,"Production assistant, television",1979-12-11,278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0,6,6,12
1296672,1296672,2020-06-21 12:12:32,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,Christopher,Castaneda,M,1632 Cohen Drive Suite 639,...,Naval architect,1967-08-30,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0,6,6,12
1296673,1296673,2020-06-21 12:13:36,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Joseph,Murray,M,42933 Ryan Underpass,...,Volunteer coordinator,1980-08-18,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0,6,6,12
1296674,1296674,2020-06-21 12:13:37,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Jeffrey,Smith,M,135 Joseph Mountains,...,"Therapist, horticultural",1995-08-16,8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0,6,6,12

In [11]:
unscaled_data['dob']= pd.to_datetime(unscaled_data['dob'])
unscaled_data['age'] = (unscaled_data['trans_date_trans_time'] - unscaled_data['dob']).dt.days//365

In [12]:
unscaled_data =unscaled_data.drop(unscaled_data[['trans_date_trans_time','dob']],axis=1)

In [13]:
unscaled_data =unscaled_data.drop('Unnamed: 0', axis =1)

In [14]:
#check point 
new_unscaled_data = unscaled_data.copy()

In [15]:
new_unscaled_data.head()

,cc_num,merchant,category,amt,first,last,gender,street,city,state,...,job,trans_num,unix_time,merch_lat,merch_long,is_fraud,month,day_of_week,hours,age
0,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,NC,...,"Psychologist, counselling",0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,1,1,0,30
1,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,WA,...,Special educational needs teacher,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,1,1,0,40
2,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,ID,...,Nature conservation officer,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,1,1,0,56
3,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,MT,...,Patent attorney,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,1,1,0,52
4,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,VA,...,Dance movement psychotherapist,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,1,1,0,32

In [16]:
new_unscaled_data['gender'] = new_unscaled_data['gender'].map({'M':0,'F':1})

In [17]:
new_unscaled_data

,cc_num,merchant,category,amt,first,last,gender,street,city,state,...,job,trans_num,unix_time,merch_lat,merch_long,is_fraud,month,day_of_week,hours,age
0,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,1,561 Perry Cove,Moravian Falls,NC,...,"Psychologist, counselling",0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,1,1,0,30
1,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,1,43039 Riley Greens Suite 393,Orient,WA,...,Special educational needs teacher,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,1,1,0,40
2,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,0,594 White Dale Suite 530,Malad City,ID,...,Nature conservation officer,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,1,1,0,56
3,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,0,9443 Cynthia Court Apt. 038,Boulder,MT,...,Patent attorney,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,1,1,0,52
4,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,0,408 Bradley Rest,Doe Hill,VA,...,Dance movement psychotherapist,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,1,1,0,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,30263540414123,fraud_Reichel Inc,entertainment,15.56,Erik,Patterson,0,162 Jessica Row Apt. 072,Hatch,UT,...,Geoscientist,440b587732da4dc1a6395aba5fb41669,1371816728,36.841266,-111.690765,0,6,6,12,58
1296671,6011149206456997,fraud_Abernathy and Sons,food_dining,51.70,Jeffrey,White,0,8617 Holmes Terrace Suite 651,Tuscarora,MD,...,"Production assistant, television",278000d2e0d2277d1de2f890067dcc0a,1371816739,38.906881,-78.246528,0,6,6,12,40
1296672,3514865930894695,fraud_Stiedemann Ltd,food_dining,105.93,Christopher,Castaneda,0,1632 Cohen Drive Suite 639,High Rolls Mountain Park,NM,...,Naval architect,483f52fe67fabef353d552c1e662974c,1371816752,33.619513,-105.130529,0,6,6,12,52
1296673,2720012583106919,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,Joseph,Murray,0,42933 Ryan Underpass,Manderson,SD,...,Volunteer coordinator,d667cdcbadaaed3da3f4020e83591c83,1371816816,42.788940,-103.241160,0,6,6,12,39
1296674,4292902571056973207,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,Jeffrey,Smith,0,135 Joseph Mountains,Sula,MT,...,"Therapist, horticultural",8f7c8e4ab7f25875d753b422917c98c9,1371816817,46.565983,-114.186110,0,6,6,12,24

In [18]:
new_unscaled_data['category'].unique()

array(['misc_net', 'grocery_pos', 'entertainment', 'gas_transport',
       'misc_pos', 'grocery_net', 'shopping_net', 'shopping_pos',
       'food_dining', 'personal_care', 'health_fitness', 'travel',
       'kids_pets', 'home'], dtype=object)

In [19]:
new_unscaled_data = pd.get_dummies(new_unscaled_data,columns=['category'],drop_first= True)

In [20]:
new_unscaled_data.columns.values

array(['cc_num', 'merchant', 'amt', 'first', 'last', 'gender', 'street',
       'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job',
       'trans_num', 'unix_time', 'merch_lat', 'merch_long', 'is_fraud',
       'month', 'day_of_week', 'hours', 'age', 'category_food_dining',
       'category_gas_transport', 'category_grocery_net',
       'category_grocery_pos', 'category_health_fitness', 'category_home',
       'category_kids_pets', 'category_misc_net', 'category_misc_pos',
       'category_personal_care', 'category_shopping_net',
       'category_shopping_pos', 'category_travel'], dtype=object)

In [21]:
new_unscaled_data['merchant'].unique()

array(['fraud_Rippin, Kub and Mann', 'fraud_Heller, Gutmann and Zieme',
       'fraud_Lind-Buckridge', 'fraud_Kutch, Hermiston and Farrell',
       'fraud_Keeling-Crist', 'fraud_Stroman, Hudson and Erdman',
       'fraud_Rowe-Vandervort', 'fraud_Corwin-Collins',
       'fraud_Herzog Ltd', 'fraud_Schoen, Kuphal and Nitzsche',
       'fraud_Rutherford-Mertz', 'fraud_Kerluke-Abshire',
       'fraud_Lockman Ltd', 'fraud_Kiehn Inc', 'fraud_Beier-Hyatt',
       'fraud_Schmidt and Sons', 'fraud_Lebsack and Sons',
       'fraud_Mayert Group', 'fraud_Konopelski, Schneider and Hartmann',
       'fraud_Schultz, Simonis and Little', 'fraud_Bauch-Raynor',
       'fraud_Harris Inc', 'fraud_Kling-Grant', 'fraud_Pacocha-Bauch',
       'fraud_Lesch Ltd', 'fraud_Kunde-Sanford', "fraud_Deckow-O'Conner",
       'fraud_Bruen-Yost', 'fraud_Kunze Inc',
       'fraud_Nitzsche, Kessler and Wolff',
       'fraud_Kihn, Abernathy and Douglas', 'fraud_Torphy-Goyette',
       'fraud_Balistreri-Nader', 'fraud_Bahringer, Schoen and Corkery',
       'fraud_Hudson-Ratke', 'fraud_Heidenreich PLC',
       'fraud_Halvorson Group', 'fraud_Harber Inc',
       'fraud_Mosciski, Gislason and Mertz',
       'fraud_Christiansen, Goyette and Schamberger', 'fraud_Howe Ltd',
       'fraud_Ledner-Pfannerstill', 'fraud_Koepp-Witting',
       'fraud_Doyle Ltd', 'fraud_Schaefer, Maggio and Daugherty',
       'fraud_Stracke-Lemke', 'fraud_Mosciski, Ziemann and Farrell',
       'fraud_Cartwright-Harris', "fraud_Pacocha-O'Reilly",
       'fraud_Pfeffer LLC', 'fraud_Huels-Hahn', 'fraud_Volkman PLC',
       'fraud_Kiehn-Emmerich', 'fraud_Kemmer-Buckridge',
       'fraud_Cummerata-Jones', 'fraud_Goldner, Kovacek and Abbott',
       'fraud_Spinka-Welch', 'fraud_Huel-Langworth',
       'fraud_Macejkovic-Lesch', 'fraud_Morar Inc',
       'fraud_Eichmann, Bogan and Rodriguez',
       'fraud_Huel, Hammes and Witting', 'fraud_Ferry, Lynch and Kautzer',
       'fraud_Heathcote LLC', 'fraud_Little, Gutmann and Lynch',
       'fraud_Jaskolski-Dibbert', 'fraud_Hackett-Lueilwitz',
       'fraud_Cummings LLC', 'fraud_Swaniawski, Lowe and Robel',
       'fraud_Osinski, Ledner and Leuschke',
       'fraud_Reichert, Huels and Hoppe', 'fraud_Ankunding LLC',
       'fraud_Pfeffer and Sons', 'fraud_Greenholt, Jacobi and Gleason',
       'fraud_Connelly, Reichert and Fritsch', 'fraud_Torp-Labadie',
       'fraud_Wolf Inc', 'fraud_VonRueden Group', 'fraud_Vandervort-Funk',
       'fraud_Bernhard Inc', 'fraud_Morissette, Weber and Wiegand',
       'fraud_Brekke and Sons', 'fraud_Mraz-Herzog',
       'fraud_Padberg-Welch', 'fraud_Kutch-Hegmann',
       'fraud_Corwin-Gorczany', 'fraud_Huels-Nolan', 'fraud_DuBuque LLC',
       'fraud_Schmeler Inc', 'fraud_Schaefer, McGlynn and Bosco',
       'fraud_Williamson LLC', 'fraud_Pouros-Conroy',
       'fraud_Erdman-Kertzmann', 'fraud_Kuhn LLC',
       'fraud_Fisher-Schowalter', 'fraud_Medhurst PLC',
       'fraud_Kerluke Inc', 'fraud_Stark-Batz',
       'fraud_Gottlieb, Considine and Schultz',
       'fraud_Adams, Kovacek and Kuhlman', 'fraud_Grimes LLC',
       'fraud_Rodriguez Group', 'fraud_Wuckert-Walter',
       'fraud_Weber and Sons', 'fraud_Herman, Treutel and Dickens',
       'fraud_Rau and Sons', 'fraud_Koss and Sons',
       'fraud_Smitham-Schiller', 'fraud_Hills-Olson', 'fraud_Durgan-Auer',
       'fraud_McDermott-Rice', 'fraud_Raynor, Reinger and Hagenes',
       'fraud_Powlowski-Weimann', 'fraud_Langosh, Wintheiser and Hyatt',
       'fraud_Baumbach, Hodkiewicz and Walsh', 'fraud_Rempel Inc',
       'fraud_Bins-Rice', 'fraud_Emard Inc', 'fraud_Kutch and Sons',
       'fraud_Fisher Inc', 'fraud_Olson, Becker and Koch',
       "fraud_Friesen-D'Amore", 'fraud_Reilly, Heaney and Cole',
       'fraud_Boyer PLC', 'fraud_Luettgen PLC', 'fraud_Cassin-Harvey',
       'fraud_Funk Group', 'fraud_Goodwin-Nitzsche',
       'fraud_Parisian, Schiller and Altenwerth', 'fraud_Metz-Boehm',
       'fraud_Monahan, Bogisich and Ledner', 'fraud_Koelpin and Sons',
       'fraud_Kuhic LLC', 'fraud_Koepp-Parker',
       'fraud_Stehr, Jewess and Schimmel',
       'fraud_Quitzon, Green and Bashirian',
       'fraud_Nicolas, Hills and McGlynn', 'fraud_Leannon-Ward',
       'fraud_Friesen-Stamm', 'fraud_Botsford Ltd', 'fraud_Bradtke PLC',
       'fraud_Zieme, Bode and Dooley', 'fraud_Hills-Witting',
       'fraud_Brown-Greenholt', 'fraud_Bernhard, Grant and Langworth',
       'fraud_Wiza, Schaden and Stark', 'fraud_Buckridge PLC',
       'fraud_Kilback LLC', 'fraud_Spinka Inc',
       'fraud_Kerluke, Kertzmann and Wiza',
       'fraud_Ferry, Reichel and DuBuque', 'fraud_Price Inc',
       'fraud_Johnston, Nikolaus and Maggio', 'fraud_Berge LLC',
       'fraud_Conroy-Cruickshank', 'fraud_Abshire PLC',
       'fraud_Gleason-Macejkovic', 'fraud_McGlynn-Jaskolski',
       'fraud_Bartoletti-Wunsch', 'fraud_Cole PLC',
       'fraud_Lehner, Reichert and Mills', 'fraud_McCullough LLC',
       'fraud_Schmitt Ltd', 'fraud_Pouros-Haag',
       'fraud_Strosin-Cruickshank', 'fraud_Weimann, Kuhic and Beahan',
       'fraud_Donnelly PLC', 'fraud_Lockman, West and Runte',
       'fraud_Torp-Lemke', 'fraud_Kris-Weimann',
       'fraud_Rodriguez, Yost and Jenkins', 'fraud_Wiegand-Lowe',
       'fraud_Auer-Mosciski', 'fraud_Okuneva, Schneider and Rau',
       'fraud_Kassulke PLC', 'fraud_Dach-Nader', 'fraud_Cummings Group',
       'fraud_Reichert, Shanahan and Hayes',
       'fraud_Tromp, Kerluke and Glover',
       'fraud_Bins, Balistreri and Beatty', 'fraud_Trantow PLC',
       'fraud_Miller-Hauck', 'fraud_Kuvalis Ltd', 'fraud_Dickinson Ltd',
       'fraud_Stanton, Jakubowski and Baumbach',
       'fraud_Rohan, White and Aufderhar',
       'fraud_Cormier, Stracke and Thiel',
       'fraud_Tillman, Fritsch and Schmitt',
       'fraud_Christiansen-Gusikowski',
       'fraud_Jenkins, Hauck and Friesen', 'fraud_Reichel Inc',
       'fraud_Prohaska-Murray', 'fraud_Parker, Nolan and Trantow',
       'fraud_Volkman Ltd', 'fraud_Streich, Hansen and Veum',
       'fraud_Kutch LLC', 'fraud_Barton Inc', 'fraud_Dooley-Thompson',
       'fraud_Flatley Group', 'fraud_Turcotte-Halvorson',
       'fraud_Lynch Ltd', 'fraud_Romaguera, Cruickshank and Greenholt',
       'fraud_Gutmann Ltd', 'fraud_Sporer Inc',
       'fraud_Runolfsson and Sons', 'fraud_Block Group',
       'fraud_Bahringer-Larson', 'fraud_Rowe, Batz and Goodwin',
       'fraud_Schmitt Inc', 'fraud_Maggio-Fahey',
       'fraud_Haley, Jewess and Bechtelar',
       'fraud_Ruecker, Beer and Collier',
       'fraud_Robel, Cummerata and Prosacco', 'fraud_Jast-McDermott',
       'fraud_Bernier, Volkman and Hoeger', 'fraud_Heaney-Marquardt',
       'fraud_Hudson-Grady', 'fraud_Towne, Walker and Borer',
       'fraud_Terry-Huel', 'fraud_Kihn-Fritsch', 'fraud_Eichmann-Russel',
       'fraud_Miller-Harris', 'fraud_Schumm PLC',
       'fraud_Greenfelder, Bartoletti and Davis',
       'fraud_Kovacek, Dibbert and Ondricka', 'fraud_Hermann-Gaylord',
       'fraud_Bailey-Morar', 'fraud_McDermott-Weimann', 'fraud_Welch Inc',
       'fraud_Auer-West', 'fraud_Boehm, Predovic and Reinger',
       'fraud_Dibbert and Sons', 'fraud_Lind, Huel and McClure',
       'fraud_Casper, Hand and Zulauf', 'fraud_McCullough Group',
       'fraud_Streich, Dietrich and Barton', "fraud_O'Keefe-Hudson",
       'fraud_Pagac LLC', 'fraud_Bernier, Streich and Jewess',
       "fraud_Greenholt, O'Hara and Balistreri", 'fraud_Dickinson-Rempel',
       'fraud_Dare-Marvin', 'fraud_Spencer PLC', 'fraud_Stamm-Rodriguez',
       'fraud_Langworth, Boehm and Gulgowski',
       'fraud_Larkin, Stracke and Greenfelder',
       'fraud_Yost, Block and Koepp',
       'fraud_Douglas, Schneider and Turner', 'fraud_Kuphal-Predovic',
       'fraud_Parisian and Sons', 'fraud_Flatley-Durgan',
       'fraud_Gislason Group', 'fraud_Bednar Group',
       'fraud_Heller-Langosh', 'fraud_Zboncak Ltd', 'fraud_Gerlach Inc',
       'fraud_Wilkinson Ltd', 'fraud_Moen, Reinger and Murphy',
       'fraud_Kerluke, Considine and Macejkovic', 'fraud_Upton PLC',
       'fraud_Bogisich Inc', 'fraud_Marks Inc', 'fraud_Murray-Smitham',
       'fraud_Frami Group', 'fraud_Ortiz Group', 'fraud_Goldner-Lemke',
       'fraud_Hickle Group', 'fraud_Conroy Ltd',
       'fraud_Schumm, Bauch and Ondricka', 'fraud_McGlynn-Heathcote',
       'fraud_Herman Inc', 'fraud_Gutmann-Upton',
       'fraud_Volkman-Predovic',
       'fraud_Wintheiser, Dietrich and Schimmel',
       'fraud_Raynor, Feest and Miller', 'fraud_Bogisich-Homenick',
       'fraud_Jast and Sons', 'fraud_Baumbach, Strosin and Nicolas',
       'fraud_Towne, Greenholt and Koepp', "fraud_Schamberger-O'Keefe",
       'fraud_Nienow PLC', 'fraud_Emmerich-Luettgen', 'fraud_Mante Group',
       'fraud_Baumbach, Feeney and Morar', 'fraud_Thiel PLC',
       'fraud_Mohr Inc', 'fraud_Hagenes, Kohler and Hoppe',
       'fraud_Block-Parisian', 'fraud_Dooley Inc',
       'fraud_Bashirian Group', 'fraud_Cremin, Hamill and Reichel',
       'fraud_Sawayn PLC', 'fraud_Jewess LLC', 'fraud_Roberts-Beahan',
       'fraud_Brown PLC', 'fraud_Tillman, Dickinson and Labadie',
       'fraud_Reichert, Rowe and Mraz', 'fraud_Kilback Group',
       'fraud_Spencer-Runolfsson', 'fraud_Labadie, Treutel and Bode',
       'fraud_Dach-Borer', 'fraud_Johnson, Runolfsdottir and Mayer',
       'fraud_Smitham-Boehm', 'fraud_Moore, Dibbert and Koepp',
       'fraud_Hamill-Daugherty', 'fraud_Watsica, Haag and Considine',
       'fraud_Smith-Stokes', 'fraud_Kuhic, Bins and Pfeffer',
       'fraud_Nader-Heller', 'fraud_Kozey-Boehm', 'fraud_Stiedemann Inc',
       'fraud_Lehner, Mosciski and King', 'fraud_Reynolds-Schinner',
       'fraud_Koss, McLaughlin and Mayer', 'fraud_Terry, Johns and Bins',
       'fraud_Kemmer-Reinger', 'fraud_Larson-Moen', 'fraud_Kuhic Inc',
       'fraud_Kris-Padberg', 'fraud_Schmeler, Bashirian and Price',
       'fraud_Klocko LLC', 'fraud_Schaefer, Fay and Hilll',
       'fraud_Kling Inc', 'fraud_Turner and Sons', 'fraud_Mohr-Bayer',
       'fraud_Wiza LLC', 'fraud_Skiles-Ankunding',
       'fraud_Jaskolski-Vandervort', 'fraud_Kerluke PLC',
       'fraud_Ernser-Lynch', 'fraud_Zboncak, Rowe and Murazik',
       'fraud_Stoltenberg-Beatty', 'fraud_Kuphal-Bartoletti',
       'fraud_Rempel PLC', 'fraud_Denesik and Sons', 'fraud_Goyette Inc',
       'fraud_Dicki Ltd', 'fraud_Stokes, Christiansen and Sipes',
       'fraud_Hermann and Sons', 'fraud_Gibson-Deckow',
       'fraud_Douglas-White', 'fraud_Murray Ltd', 'fraud_McKenzie-Huels',
       'fraud_Runte-Mohr', 'fraud_Roob, Conn and Tremblay',
       'fraud_Boyer-Reichert', 'fraud_Shanahan-Lehner',
       'fraud_Greenholt Ltd', 'fraud_Kulas Group',
       'fraud_Dare, Fritsch and Zboncak', 'fraud_Waters-Cruickshank',
       'fraud_Kunze, Larkin and Mayert', 'fraud_Bednar Inc',
       'fraud_Schimmel-Olson', 'fraud_Lubowitz, Terry and Stracke',
       'fraud_Schoen-Quigley', 'fraud_Kihn-Schuster',
       'fraud_Padberg-Rogahn', 'fraud_Lynch-Mohr', 'fraud_Hilpert-Conroy',
       'fraud_Jacobi Inc', 'fraud_Berge, Kautzer and Harris',
       'fraud_Hammes-Beatty', 'fraud_Gulgowski LLC',
       'fraud_Schuppe, Nolan and Hoeger', 'fraud_Pollich LLC',
       'fraud_Bernier and Sons', 'fraud_Wilkinson PLC',
       'fraud_Kling-Ernser', "fraud_O'Connell, Botsford and Hand",
       'fraud_Little-Gleichner', 'fraud_Champlin and Sons',
       'fraud_Hoppe-Parisian', 'fraud_Schuppe LLC', 'fraud_Emmerich-Rau',
       'fraud_Beier LLC', 'fraud_Champlin-Casper', 'fraud_Gerhold LLC',
       'fraud_Renner Ltd', 'fraud_Gaylord-Powlowski',
       'fraud_Prosacco, Kreiger and Kovacek', 'fraud_Eichmann-Kilback',
       "fraud_O'Hara-Wilderman", 'fraud_Terry Ltd',
       'fraud_Beier and Sons', "fraud_O'Keefe-Wisoky",
       'fraud_Simonis-Prohaska', 'fraud_Breitenberg-Hermiston',
       'fraud_Brown Inc', 'fraud_Fahey Inc',
       'fraud_Boehm, Block and Jakubowski',
       'fraud_Mante, Luettgen and Hackett', 'fraud_Thompson-Gleason',
       'fraud_Turcotte, Batz and Buckridge',
       'fraud_Goyette, Howell and Collier',
       'fraud_Jones, Sawayn and Romaguera', 'fraud_Medhurst Inc',
       'fraud_Bode-Schuster', 'fraud_Connelly-Carter',
       'fraud_Gottlieb-Hansen', 'fraud_Schroeder, Wolff and Hermiston',
       'fraud_Hettinger, McCullough and Fay',
       'fraud_Pouros, Walker and Spencer', 'fraud_Kub PLC',
       'fraud_Watsica LLC', 'fraud_Stiedemann Ltd',
       'fraud_Hauck, Dietrich and Funk', 'fraud_Labadie LLC',
       'fraud_Friesen Inc', 'fraud_Crist, Jakubowski and Littel',
       'fraud_Hodkiewicz, Prohaska and Paucek',
       'fraud_McDermott, Osinski and Morar', 'fraud_Fritsch and Sons',
       'fraud_Swaniawski, Nitzsche and Welch',
       'fraud_Windler, Goodwin and Kovacek',
       'fraud_Yost, Schamberger and Windler',
       'fraud_Metz, Russel and Metz', 'fraud_Erdman-Durgan',
       'fraud_Bahringer, Bergnaum and Quitzon', 'fraud_Veum-Koelpin',
       'fraud_Becker, Harris and Harvey', 'fraud_Monahan-Morar',
       'fraud_Johns Inc', 'fraud_Mosciski Group', 'fraud_Abbott-Steuber',
       'fraud_Schaefer Ltd', 'fraud_Dibbert-Green',
       'fraud_Weimann-Lockman', 'fraud_Kub-Heaney', 'fraud_Zulauf LLC',
       'fraud_Ratke and Sons', 'fraud_Jakubowski Inc', 'fraud_Beer-Jast',
       'fraud_Kautzer and Sons', 'fraud_Feil-Morar',
       'fraud_Johnston-Casper', 'fraud_Medhurst, Labadie and Gottlieb',
       "fraud_Lesch, D'Amore and Brown", 'fraud_Botsford PLC',
       'fraud_Bins-Howell', 'fraud_Kihn Inc',
       'fraud_Hartmann, Rowe and Hermann', 'fraud_Towne LLC',
       'fraud_Lynch-Wisozk', 'fraud_Kutch-Ferry', 'fraud_Goyette-Gerhold',
       'fraud_Bradtke, Torp and Bahringer', 'fraud_Homenick LLC',
       'fraud_Zemlak, Tillman and Cremin',
       'fraud_Schneider, Hayes and Nikolaus',
       'fraud_Schumm, McLaughlin and Carter', 'fraud_Nader-Maggio',
       'fraud_Haley, Batz and Auer', 'fraud_Yost-Rogahn',
       'fraud_Schoen, Nienow and Bauch',
       'fraud_Ledner, Hartmann and Feest', 'fraud_Collier LLC',
       'fraud_Schuppe-Schuppe', 'fraud_Walter, Hettinger and Kessler',
       'fraud_Bechtelar-Rippin', "fraud_Hamill-D'Amore",
       'fraud_Swift PLC', 'fraud_Cronin, Kshlerin and Weber',
       'fraud_Romaguera, Wehner and Tromp',
       'fraud_Feil, Hilpert and Koss', 'fraud_White and Sons',
       'fraud_Mueller, Gerhold and Mueller', 'fraud_Botsford and Sons',
       'fraud_Kirlin and Sons', 'fraud_Bednar PLC',
       'fraud_Runolfsdottir, Mueller and Hand', 'fraud_Kuphal-Toy',
       'fraud_Bahringer-Streich', 'fraud_Wuckert, Wintheiser and Friesen',
       'fraud_Crona and Sons', 'fraud_Prosacco LLC', 'fraud_Schiller Ltd',
       'fraud_Waelchi-Wolf', 'fraud_Torphy-Kertzmann',
       'fraud_McCullough, Hudson and Schuster', 'fraud_Baumbach Ltd',
       'fraud_Schiller, Blanda and Johnson', 'fraud_Cartwright PLC',
       'fraud_Reilly LLC', 'fraud_Cruickshank-Mills',
       'fraud_Altenwerth, Cartwright and Koss',
       'fraud_Effertz, Welch and Schowalter',
       'fraud_Klocko, Runolfsdottir and Breitenberg',
       'fraud_Ruecker-Mayert', 'fraud_Schroeder, Hauck and Treutel',
       'fraud_Lemke-Gutmann', 'fraud_Graham, Hegmann and Hammes',
       'fraud_Reilly and Sons', 'fraud_Stark-Koss', 'fraud_Daugherty LLC',
       'fraud_Denesik, Powlowski and Pouros', 'fraud_Rippin-VonRueden',
       'fraud_Heller PLC', 'fraud_Hills-Boyer', 'fraud_Cormier LLC',
       'fraud_Erdman-Ebert', 'fraud_Bogisich-Weimann',
       'fraud_Gutmann, McLaughlin and Wiza', 'fraud_Little Ltd',
       'fraud_Bode-Rempel', 'fraud_Kutch, Steuber and Gerhold',
       'fraud_Kessler Inc', 'fraud_Deckow-Dare', 'fraud_Rolfson-Kunde',
       'fraud_Marvin-Lind', 'fraud_Barrows PLC', 'fraud_Abbott-Rogahn',
       'fraud_Ziemann-Waters', 'fraud_Reinger, Weissnat and Strosin',
       'fraud_Heathcote, Yost and Kertzmann', 'fraud_Will Ltd',
       'fraud_Kutch-Wilderman', 'fraud_Hermiston, Russel and Price',
       'fraud_Schmidt-Larkin', 'fraud_Lang, Towne and Schuppe',
       'fraud_Weber, Thiel and Hammes',
       'fraud_Hahn, Bahringer and McLaughlin',
       'fraud_Koss, Hansen and Lueilwitz',
       'fraud_Roberts, Ryan and Smith', 'fraud_Hintz, Bauch and Smith',
       'fraud_Monahan, Hermann and Johns',
       'fraud_Bahringer, Osinski and Block',
       'fraud_Douglas, DuBuque and McKenzie', 'fraud_Hackett Group',
       'fraud_Schmeler-Howe', 'fraud_Predovic Inc', 'fraud_Langworth LLC',
       'fraud_Bartoletti and Sons', 'fraud_Bernhard-Lesch',
       'fraud_Satterfield-Lowe', 'fraud_Runte, Green and Emard',
       'fraud_Lowe, Dietrich and Erdman', 'fraud_Jast Ltd',
       'fraud_Welch, Rath and Koepp', 'fraud_Skiles LLC',
       'fraud_Ernser-Feest', 'fraud_Klein Group',
       'fraud_Torp, Muller and Borer', 'fraud_Kuhn Group',
       'fraud_Streich, Rolfson and Wilderman', 'fraud_Bins-Tillman',
       'fraud_Ankunding-Carroll', 'fraud_Hahn, Douglas and Schowalter',
       'fraud_Witting, Beer and Ernser', 'fraud_Morissette LLC',
       'fraud_Berge-Hills', 'fraud_Donnelly LLC', 'fraud_Zboncak LLC',
       'fraud_Turner, Ziemann and Lehner', 'fraud_Padberg-Sauer',
       'fraud_Schulist Ltd', 'fraud_Rau-Grant', 'fraud_Osinski Inc',
       'fraud_Berge-Ullrich', 'fraud_Wuckert-Goldner',
       'fraud_Kertzmann LLC', 'fraud_Daugherty, Pouros and Beahan',
       'fraud_Armstrong, Walter and Gottlieb', 'fraud_Conroy-Emard',
       'fraud_Moore, Williamson and Emmerich', 'fraud_Gleason and Sons',
       'fraud_Roberts, Daniel and Macejkovic', 'fraud_Turner LLC',
       'fraud_Crooks and Sons', 'fraud_Waelchi Inc',
       'fraud_Hoppe, Harris and Bednar', 'fraud_Effertz LLC',
       'fraud_Lubowitz-Walter', 'fraud_Hyatt-Blick', 'fraud_Carroll PLC',
       'fraud_Lemke and Sons', 'fraud_Treutel-King',
       'fraud_Fadel-Hilpert', 'fraud_Altenwerth-Kilback',
       'fraud_Bauch-Blanda', 'fraud_Sporer-Keebler', 'fraud_Hirthe-Beier',
       'fraud_Wisozk and Sons', 'fraud_Streich Ltd', 'fraud_Schoen Ltd',
       'fraud_Windler LLC', 'fraud_Nolan-Williamson',
       'fraud_Roob-Okuneva', 'fraud_Lakin, Ferry and Beatty',
       'fraud_Gottlieb Group', 'fraud_Harris Group', 'fraud_Fritsch LLC',
       'fraud_Corwin-Romaguera', 'fraud_Dietrich-Fadel',
       'fraud_Kling, Howe and Schneider', 'fraud_Kozey-Kuhlman',
       'fraud_Graham and Sons', 'fraud_Jacobi and Sons',
       'fraud_Eichmann, Hayes and Treutel',
       'fraud_Brown, Homenick and Lesch', 'fraud_Erdman-Schaden',
       'fraud_Durgan, Gislason and Spencer', 'fraud_Friesen-Ortiz',
       'fraud_Morissette-Schaefer', 'fraud_Nienow, Ankunding and Collier',
       'fraud_Cole, Hills and Jewess',
       'fraud_Conroy, Balistreri and Gorczany',
       'fraud_Reichel, Bradtke and Blanda',
       "fraud_O'Reilly, Mohr and Purdy", 'fraud_Ullrich Ltd',
       'fraud_Schroeder Group', 'fraud_Boyer-Haley',
       'fraud_Dare, Casper and Bartoletti',
       'fraud_Medhurst, Cartwright and Ebert', 'fraud_Quitzon-Goyette',
       'fraud_Wilkinson LLC', 'fraud_Romaguera and Sons',
       'fraud_Larkin Ltd', 'fraud_Fadel, Mertz and Rippin',
       'fraud_Huel Ltd', 'fraud_Cummerata-Hilpert', 'fraud_Zemlak Group',
       'fraud_Dare-Gibson', 'fraud_Adams-Barrows', 'fraud_Block-Hauck',
       'fraud_Howe PLC', 'fraud_Leffler-Goldner', 'fraud_Tillman LLC',
       'fraud_Pacocha-Weissnat', 'fraud_Morissette PLC',
       'fraud_Jerde-Hermann', 'fraud_Kihn, Brakus and Goyette',
       'fraud_Hills, Hegmann and Schaefer', 'fraud_Friesen Ltd',
       'fraud_Kilback and Sons', 'fraud_Ebert-Daugherty',
       'fraud_Hermiston, Pacocha and Smith', 'fraud_Auer LLC',
       'fraud_Fadel Inc', 'fraud_Daugherty-Thompson',
       'fraud_Romaguera Ltd', 'fraud_Parker-Kunde', 'fraud_Barton LLC',
       'fraud_Kassulke Inc', 'fraud_McLaughlin, Armstrong and Koepp',
       'fraud_Abernathy and Sons', 'fraud_Bahringer Group',
       'fraud_Connelly PLC', 'fraud_Willms, Kris and Bergnaum',
       'fraud_Thiel Ltd', 'fraud_Kris-Kertzmann',
       "fraud_O'Connell-Ullrich", 'fraud_Kozey-McDermott',

In [22]:
for col in ['merchant','job','city','state']:
 print(col,'->',new_unscaled_data[col].nunique())

merchant -> 693
job -> 494
city -> 894
state -> 51

In [23]:
merchant_freq = new_unscaled_data['merchant'].value_counts()
new_unscaled_data['merchant_freq'] = new_unscaled_data['merchant'].map(merchant_freq)

job_freq = new_unscaled_data['job'].value_counts()
new_unscaled_data['job_freq'] = new_unscaled_data['job'].map(job_freq)

city_freq = new_unscaled_data['city'].value_counts()
new_unscaled_data['city_freq'] = new_unscaled_data['city'].map(city_freq)

state_freq = new_unscaled_data['state'].value_counts()
new_unscaled_data['state_freq'] = new_unscaled_data['state'].map(state_freq)

In [24]:
new_unscaled_data.drop(['merchant','job','city','state'],axis=1,inplace=True)

In [25]:
new_unscaled_data.head(2)
new_unscaled_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296675 entries, 0 to 1296674
Data columns (total 36 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   cc_num                   1296675 non-null  int64
 1   amt                      1296675 non-null  float64
 2   first                    1296675 non-null  object
 3   last                     1296675 non-null  object
 4   gender                   1296675 non-null  int64
 5   street                   1296675 non-null  object
 6   zip                      1296675 non-null  int64
 7   lat                      1296675 non-null  float64
 8   long                     1296675 non-null  float64
 9   city_pop                 1296675 non-null  int64
 10  trans_num                1296675 non-null  object
 11  unix_time                1296675 non-null  int64
 12  merch_lat                1296675 non-null  float64
 13  merch_long               1296675 non-null  float64
 14  is_fraud                 1296675 non-null  int64
 15  month                    1296675 non-null  int32
 16  day_of_week              1296675 non-null  int32
 17  hours                    1296675 non-null  int32
 18  age                      1296675 non-null  int64
 19  category_food_dining     1296675 non-null  bool
 20  category_gas_transport   1296675 non-null  bool
 21  category_grocery_net     1296675 non-null  bool
 22  category_grocery_pos     1296675 non-null  bool
 23  category_health_fitness  1296675 non-null  bool
 24  category_home            1296675 non-null  bool
 25  category_kids_pets       1296675 non-null  bool
 26  category_misc_net        1296675 non-null  bool
 27  category_misc_pos        1296675 non-null  bool
 28  category_personal_care   1296675 non-null  bool
 29  category_shopping_net    1296675 non-null  bool
 30  category_shopping_pos    1296675 non-null  bool
 31  category_travel          1296675 non-null  bool
 32  merchant_freq            1296675 non-null  int64
 33  job_freq                 1296675 non-null  int64
 34  city_freq                1296675 non-null  int64
 35  state_freq               1296675 non-null  int64
dtypes: bool(13), float64(5), int32(3), int64(11), object(4)
memory usage: 228.8+ MB

In [26]:
new_unscaled_data.columns.values

array(['cc_num', 'amt', 'first', 'last', 'gender', 'street', 'zip', 'lat',
       'long', 'city_pop', 'trans_num', 'unix_time', 'merch_lat',
       'merch_long', 'is_fraud', 'month', 'day_of_week', 'hours', 'age',
       'category_food_dining', 'category_gas_transport',
       'category_grocery_net', 'category_grocery_pos',
       'category_health_fitness', 'category_home', 'category_kids_pets',
       'category_misc_net', 'category_misc_pos', 'category_personal_care',
       'category_shopping_net', 'category_shopping_pos',
       'category_travel', 'merchant_freq', 'job_freq', 'city_freq',
       'state_freq'], dtype=object)

In [27]:
new_unscaled_data.head(2)

,cc_num,amt,first,last,gender,street,zip,lat,long,city_pop,...,category_misc_net,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,merchant_freq,job_freq,city_freq,state_freq
0,2703186189652095,4.97,Jennifer,Banks,1,561 Perry Cove,28654,36.0788,-81.1781,3495,...,True,False,False,False,False,False,1267,3545,2028,30266
1,630423337322,107.23,Stephanie,Gill,1,43039 Riley Greens Suite 393,99160,48.8878,-118.2105,149,...,False,False,False,False,False,False,2503,5099,3545,18924

In [28]:
import numpy as np

def haversine_distance(lat1, lon1, lat2, lon2):
    # Convert degrees to radians
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    
    a = np.sin(dlat/2)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2)**2
    c = 2 * np.arcsin(np.sqrt(a))
    
    earth_radius_km = 6371
    return earth_radius_km * c

new_unscaled_data['distance_km'] = haversine_distance(new_unscaled_data['lat'], new_unscaled_data['long'], new_unscaled_data['merch_lat'], new_unscaled_data['merch_long'])

In [29]:
new_unscaled_data.head(2)

,cc_num,amt,first,last,gender,street,zip,lat,long,city_pop,...,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,merchant_freq,job_freq,city_freq,state_freq,distance_km
0,2703186189652095,4.97,Jennifer,Banks,1,561 Perry Cove,28654,36.0788,-81.1781,3495,...,False,False,False,False,False,1267,3545,2028,30266,78.597568
1,630423337322,107.23,Stephanie,Gill,1,43039 Riley Greens Suite 393,99160,48.8878,-118.2105,149,...,False,False,False,False,False,2503,5099,3545,18924,30.212176

In [30]:
#check point 2
new_unscaled_data2 = new_unscaled_data.drop(['lat', 'long', 'merch_lat', 'merch_long'], axis=1)

In [31]:
new_unscaled_data2['unix_time']

0          1325376018
1          1325376044
2          1325376051
3          1325376076
4          1325376186
              ...
1296670    1371816728
1296671    1371816739
1296672    1371816752
1296673    1371816816
1296674    1371816817
Name: unix_time, Length: 1296675, dtype: int64

In [32]:
new_unscaled_data2.columns.values

array(['cc_num', 'amt', 'first', 'last', 'gender', 'street', 'zip',
       'city_pop', 'trans_num', 'unix_time', 'is_fraud', 'month',
       'day_of_week', 'hours', 'age', 'category_food_dining',
       'category_gas_transport', 'category_grocery_net',
       'category_grocery_pos', 'category_health_fitness', 'category_home',
       'category_kids_pets', 'category_misc_net', 'category_misc_pos',
       'category_personal_care', 'category_shopping_net',
       'category_shopping_pos', 'category_travel', 'merchant_freq',
       'job_freq', 'city_freq', 'state_freq', 'distance_km'], dtype=object)

In [33]:
new_unscaled_data2 = new_unscaled_data2.drop(['trans_num', 'street', 'zip', 'unix_time'], axis=1)

In [34]:
new_unscaled_data2.columns.values

array(['cc_num', 'amt', 'first', 'last', 'gender', 'city_pop', 'is_fraud',
       'month', 'day_of_week', 'hours', 'age', 'category_food_dining',
       'category_gas_transport', 'category_grocery_net',
       'category_grocery_pos', 'category_health_fitness', 'category_home',
       'category_kids_pets', 'category_misc_net', 'category_misc_pos',
       'category_personal_care', 'category_shopping_net',
       'category_shopping_pos', 'category_travel', 'merchant_freq',
       'job_freq', 'city_freq', 'state_freq', 'distance_km'], dtype=object)

In [35]:
new_unscaled_data2

,cc_num,amt,first,last,gender,city_pop,is_fraud,month,day_of_week,hours,...,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,merchant_freq,job_freq,city_freq,state_freq,distance_km
0,2703186189652095,4.97,Jennifer,Banks,1,3495,0,1,1,0,...,False,False,False,False,False,1267,3545,2028,30266,78.597568
1,630423337322,107.23,Stephanie,Gill,1,149,0,1,1,0,...,False,False,False,False,False,2503,5099,3545,18924,30.212176
2,38859492057661,220.11,Edward,Sanchez,0,4154,0,1,1,0,...,False,False,False,False,False,1895,511,503,5545,108.206083
3,3534093764340240,45.00,Jeremy,White,0,1939,0,1,1,0,...,False,False,False,False,False,2613,2530,493,11754,95.673231
4,375534208663984,41.96,Tyler,Garcia,0,99,0,1,1,0,...,True,False,False,False,False,1592,2017,2017,29250,77.556744
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1296670,30263540414123,15.56,Erik,Patterson,0,258,0,6,6,12,...,False,False,False,False,False,1907,5620,1513,10699,119.752136
1296671,6011149206456997,51.70,Jeffrey,White,0,100,0,6,6,12,...,False,False,False,False,False,1751,531,531,26193,75.104085
1296672,3514865930894695,105.93,Christopher,Castaneda,0,899,0,6,6,12,...,False,False,False,False,False,1853,8684,2070,16407,99.047734
1296673,2720012583106919,74.90,Joseph,Murray,0,1126,0,6,6,12,...,False,False,False,False,False,1910,2024,2024,12324,84.627652
1296674,4292902571056973207,4.30,Jeffrey,Smith,0,218,0,6,6,12,...,False,False,False,False,False,1788,2528,1512,11754,83.853655

In [36]:
new_unscaled_data2 = new_unscaled_data2.drop(['cc_num','first','last'], axis=1)

In [37]:
new_unscaled_data2.head(2)

,amt,gender,city_pop,is_fraud,month,day_of_week,hours,age,category_food_dining,category_gas_transport,...,category_misc_pos,category_personal_care,category_shopping_net,category_shopping_pos,category_travel,merchant_freq,job_freq,city_freq,state_freq,distance_km
0,4.97,1,3495,0,1,1,0,30,False,False,...,False,False,False,False,False,1267,3545,2028,30266,78.597568
1,107.23,1,149,0,1,1,0,40,False,False,...,False,False,False,False,False,2503,5099,3545,18924,30.212176

In [38]:
new_unscaled_data2.shape

(1296675, 26)

In [39]:
from sklearn.model_selection import train_test_split

X = new_unscaled_data2.drop('is_fraud', axis=1)
Y = new_unscaled_data2['is_fraud']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [40]:
print(Y_test.value_counts(normalize=True)*100)
print(Y_train.value_counts(normalize=True)*100)

is_fraud
0    99.413886
1     0.586114
Name: proportion, dtype: float64
is_fraud
0    99.422947
1     0.577053
Name: proportion, dtype: float64

In [41]:
from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()
numeric_cols = ['amt', 'city_pop', 'age', 'distance_km', 'hours', 'month', 'day_of_week',
                 'merchant_freq', 'job_freq', 'city_freq', 'state_freq']


X_train[numeric_cols] = scalar.fit_transform(X_train[numeric_cols])


X_test[numeric_cols] = scalar.transform(X_test[numeric_cols])

In [42]:
from sklearn.ensemble import RandomForestClassifier
model= RandomForestClassifier(class_weight= 'balanced', random_state=42)
model.fit(X_train,Y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [43]:
y_pred = model.predict(X_test)

In [44]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Accuracy:", accuracy_score(Y_test, y_pred))
print("Classification Report:")
print(classification_report(Y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(Y_test, y_pred))

Accuracy: 0.998546281836235
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    257815
           1       0.98      0.77      0.86      1520

    accuracy                           1.00    259335
   macro avg       0.99      0.88      0.93    259335
weighted avg       1.00      1.00      1.00    259335

Confusion Matrix:
[[257790     25]
 [   352   1168]]

In [45]:
from sklearn.metrics import average_precision_score
y_prob = model.predict_proba(X_test)[:, 1]
print(average_precision_score(Y_test, y_prob))

0.9350344938079114

In [46]:
import pandas as pd
importances = pd.Series(model.feature_importances_, index=X_train.columns)
importances.sort_values(ascending=False).head(10)

amt                       0.527610
hours                     0.172541
merchant_freq             0.047357
city_freq                 0.043296
age                       0.022031
job_freq                  0.018962
category_grocery_pos      0.018647
category_gas_transport    0.017224
category_shopping_net     0.016355
city_pop                  0.015733
dtype: float64

In [47]:
import joblib 
joblib.dump(model,'fraud_model.pkl')
joblib.dump(scalar,'scalar.pkl')

['scalar.pkl']

In [48]:
print(list(X_train.columns))

['amt', 'gender', 'city_pop', 'month', 'day_of_week', 'hours', 'age', 'category_food_dining', 'category_gas_transport', 'category_grocery_net', 'category_grocery_pos', 'category_health_fitness', 'category_home', 'category_kids_pets', 'category_misc_net', 'category_misc_pos', 'category_personal_care', 'category_shopping_net', 'category_shopping_pos', 'category_travel', 'merchant_freq', 'job_freq', 'city_freq', 'state_freq', 'distance_km']

In [51]:
!pip install imbalanced-learn -q
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state = 42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, Y_train)
print(y_train_smote.value_counts())

is_fraud
0    1031354
1    1031354
Name: count, dtype: int64

In [52]:
from sklearn.ensemble import RandomForestClassifier

model_smote = RandomForestClassifier(random_state=42)  # no class_weight needed - SMOTE already balanced it
model_smote.fit(X_train_smote, y_train_smote)

RandomForestClassifier(random_state=42)

In [53]:
from sklearn.metrics import classification_report, confusion_matrix, average_precision_score

y_pred_smote = model_smote.predict(X_test)
y_prob_smote = model_smote.predict_proba(X_test)[:, 1]

print(classification_report(Y_test, y_pred_smote))
print(confusion_matrix(Y_test, y_pred_smote))
print("PR-AUC:", average_precision_score(Y_test, y_prob_smote))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    257815
           1       0.89      0.85      0.87      1520

    accuracy                           1.00    259335
   macro avg       0.94      0.92      0.93    259335
weighted avg       1.00      1.00      1.00    259335

[[257656    159]
 [   234   1286]]
PR-AUC: 0.9235483433420807

In [55]:
y_prob_weights = model.predict_proba(X_test)[:, 1]  # your original class-weights model
print("PR-AUC (class weights):", average_precision_score(Y_test, y_prob_weights))

PR-AUC (class weights): 0.9350344938079114